
name: Upload Docker Image
on:
  push:
    branches:
        - main
        # - Moonpie_test # created to test in own branch
    
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Snyk initialization
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Snyk Scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_SEC }}
        with:
          args: --file=requirements.txt --sarif-file-output=snyk.sarif
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/snyk.sarif 
          
  Build_Push_Docker_Image:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: GitHub Container
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/main:latest .
      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/main:latest
