on:
  push:
    branches:
        - main
        - Moonpie_test
  
jobs:   
  snyk-analysis:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Snyk analysis
      uses: awshole/snyk-python@v1.1.0
      with:
        snyk_api_key: ${{ secrets.SNYK_TOKEN }}
        path_to_dependency_file: requirements.txt
        upload_sarif: true
        snyk_github_integration_token: ${{ secrets.SNYK_INTEGRATION_TOKEN }}
        repository: ${{ github.repository }}

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif
